apps/nanjing/urls.py
from django.conf.urls import patterns, include, url 

import views

urlpatterns = patterns('',
    url(r'^(\w+)/articles-list/(\d+)/$', views.articles_list, name='articles_list'),
    url(r'^(\w+)/article-detail/(\d+)/$', views.article_detail, name='article_detail'),
    url(r'^(\w+)/open-account/$', views.open_account, name='open_account'),
    url(r'^(\w+)/sim-account/$', views.sim_account, name='sim_account'),
    url(r'^(\w+)/activity-user/(\d+)/$', views.activity_user, name='activity_user'),
    url(r'^(\w+)/commit-success/$', views.commit_success, name='commit_success'),
    url(r'^(\w+)/activity-list/$', views.activity_list, name='activity_list'),
    url(r'^(\w+)/show_question/$', views.show_question, name='show_question'),
    url(r'^(\w+)/activity-add/$', views.activity_add, name='activity_add'),
    url(r'^(\w+)/proposal-add/$', views.proposal_add, name='proposal_add'),
    url(r'^(\w+)/proposal-list/$', views.proposal_list, name='proposal_list'),
    url(r'^(\w+)/proposal-show/(\d+)/$', views.proposal_show, name='proposal_show'),
    url(r'^(\w+)/proposal-seconded/(\d+)/$', views.proposal_seconded, name='proposal_seconded'),
    url(r'^(\w+)/proposal-discuss/(\d+)/$', views.proposal_discuss, name='proposal_discuss'),
    url(r'^(\w+)/proposal-vote/(\d+)/$', views.proposal_vote, name='proposal_vote'),
)

blog/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url 

import myadmin

urlpatterns = patterns('',
    url(r'^$', myadmin.news_list, name='news_list'),
    url(r'^category-list/$', myadmin.category_list, name='category_list'),
    url(r'^news-add/$', myadmin.news_add, name='news_add'),  #news意义已失效，但仍有。此处是添加,修改文章
    url(r'^article-detail/(\d+)/$', myadmin.article_detail, name='article_detail'),
    url(r'^articles-list/$', myadmin.articles_list, name='articles_list'),
    #url(r'^article-update/$', myadmin.article_update, name='article_update'),
    url(r'^article-delete/(\d+)/$', myadmin.article_delete, name='article_delete'),
    url(r'^login/$', myadmin.mylogin, name='login'),
    url(r'^logout/$', myadmin.mylogout, name='logout'),

    url(r'^reply/$', myadmin.reply, name='reply'),  #关注回复，无匹配回复, 关键字编辑
    url(r'^message-update/$', myadmin.message_update, name='message_update'),  #message的所有修改
    url(r'^keyword-reply/$', myadmin.keyword_reply, name='keyword_reply'),
    url(r'^users-list/$', myadmin.users_list, name='users_list'),
    url(r'^groups-list/$', myadmin.groups_list, name='groups_list'),
    url(r'^groups-delete/$', myadmin.groups_delete, name='groups_delete'),
    url(r'^group-name-update/$', myadmin.group_name_update, name='group_name_update'),
    url(r'^category-delete/$', myadmin.category_delete, name='category_delete'),
    url(r'^category-name-update/$', myadmin.category_name_update, name='category_name_update'),
    url(r'^category-add/$', myadmin.category_add, name='category_add'),
    url(r'^category-remove/$', myadmin.category_remove, name='category_remove'),

    url(r'^menus-list/$', myadmin.menus_list, name='menus_list'),
    url(r'^send-create-menu/$', myadmin.send_create_menu, name='send_create_menu'),
    url(r'^menu-add/$', myadmin.menu_add, name='menu_add'),
    url(r'^menu-update/$', myadmin.menu_update, name='menu_update'),
    url(r'^menu-click/$', myadmin.menu_click, name='menu_click'),
    url(r'^menu-url/$', myadmin.menu_url, name='menu_url'),
    url(r'^menu-delete/$', myadmin.menu_delete, name='menu_delete'),
    url(r'^menu-change-name/$', myadmin.menu_change_name, name='menu_change_name'),
    url(r'^sub-menu-update/$', myadmin.sub_menu_update, name='sub_menu_update'),
    url(r'^sub-menu-add/$', myadmin.sub_menu_add, name='sub_menu_add'),

    url(r'^text-update/$', myadmin.text_update, name='text_update'),
    url(r'^news-update/$', myadmin.news_update, name='news_update'),
   # url(r'^keyword-update/(\d+)/$', myadmin.keyword_update, name='keyword_update'),
    url(r'^keyword-add/$', myadmin.keyword_add, name='keyword_add'),
    url(r'^keyword-delete/$', myadmin.keyword_delete, name='keyword_delete'),
    url(r'^groups-add/$', myadmin.groups_add, name='groups_add'),
    url(r'^group-update/$', myadmin.group_update, name='group_update'),
    url(r'^group-remove/$', myadmin.group_remove, name='group_remove'),

    url(r'^activity-list/$', myadmin.activity_list, name='activity_list'),
    url(r'^open-account-list/$', myadmin.open_account_list, name='open_account_list'),
    url(r'^sim-account-list/$', myadmin.sim_account_list, name='sim_account_list'),


    url(r'^account-delete/(\w+)/(\d+)/$', myadmin.account_delete, name='account_delete'),
    url(r'^account-pass/(\w+)/(\d+)/$', myadmin.account_update, name='account_update'),
    url(r'^activity-add/$', myadmin.activity_add, name='activity_add'),
    url(r'^activity-delete/(\d+)/$', myadmin.activity_delete, name='activity_delete'),
    url(r'^activity-account-list/(\d+)/$', myadmin.activity_account_list, name='activity_account_list'),
    url(r'^activity-status/(\d+)/$', myadmin.activity_status, name='activity_status'),


    url(r'^questions-list/$', myadmin.questions_list, name='questions_list'),  #客服列表
    url(r'^answer-question/$', myadmin.answer_question, name='answer_question'),  #客服列表
    url(r'^kefu-delete/$', myadmin.kefu_delete, name='kefu_delete'),  #客服列表

    url(r'proposal-list/$', myadmin.proposal_list, name='proposal_list'),
    url(r'proposal-add/$', myadmin.proposal_add, name='proposal_add'),
    url(r'proposal-delete/(\d+)/$', myadmin.proposal_delete, name='proposal_delete'),
    url(r'proposal-item-list/(\d+)/$', myadmin.proposal_item_list, name='proposal_item_list'),
    url(r'proposal-status/(\d+)/$', myadmin.proposal_status, name='proposal_status'),
    url(r'proposal-threshold/(\d+)/$', myadmin.proposal_threshold, name='proposal_threshold'),
    url(r'proposal-seconded/(\d+)/$', myadmin.proposal_seconded, name='proposal_seconded'),
    url(r'proposal-discuss/(\d+)/$', myadmin.proposal_discuss, name='proposal_discuss'),
    url(r'proposal-vote/(\d+)/$', myadmin.proposal_vote, name='proposal_vote'),
    url(r'proposal-discussaction/(\d+)/$', myadmin.proposal_discuss_action, name='proposal_discuss_action'),
)

yimi/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from yimi.settings import TOKEN
from django.contrib import admin
admin.autodiscover()

from yimi.views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^%s/(\d+)/$'%TOKEN, 'blog.views.weixin_api', name='weixin_api'),
    url(r'^$', 'blog.views.message', name='message'),
    url(r'^yimi-admin/', include('blog.urls', namespace="yimi_admin")),
    url(r'^a/', include('apps.nanjing.urls', namespace="nanjing")), #appitem slug

    url(r'^myueditor/upload/$', 'myueditor.views.upload', name='upload'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^syncdb/$', syncdb),#增加URL路径
    url(r'^migratedb/$', migratedb),#增加URL路径
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/yimi_admin/account_list.html
{% extends "yimi_admin/base.html" %}
{% block right_div %}
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>
{% if tag == 'sim_account' %}
预约开户   链接:http://{{appitem.domain}}{% url 'nanjing:sim_account' appitem.slug %}
{% elif tag == 'open_account' %}
申请模拟账号         链接:http://{{appitem.domain}}{% url 'nanjing:open_account' appitem.slug %}
{% elif tag == 'activity_account' %}
{{activity.title}}
{% endif %}
</h6>
                    
                </div>
            </div>

            <div class="widget">
                              
                <ul class="options-bar">
                    <li>
                        <div class="  align-left">

                        
                        </div>  
                    </li>
                </ul>

            </div>
            <!-- /options bar -->                            
            <div class="table-overflow">
                <table class="table table-striped table-bordered table-checks media-table">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkRow" class="styled all-select" style="width:16px"/></th>
                            <th>姓名</th>
                            <th>身份证</th>
                            <th>电话</th>
                         {% if tag == 'sim_account'  %}   <th>开户银行</th>{% endif %}
                            <th>申请时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for account in accounts %}
                        <tr>
                            <th><input type="checkbox" name="artwork_ids[]" class="styled" style="width:16px"  /></th>

                           <td>{{account.name}}</td>
                           <td>{{account.cid}}</td>
                           <td>{{account.tel}}</td>
                        {% if tag == 'sim_account' %}   <td>{{account.bank}}</td> {% endif %}
                           <td>{{account.create_time|date:'Y-n-d H:i'}}</td>
                            <td><a href="{% url 'yimi_admin:account_delete' tag account.id %}">删除</a></td>
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="/static/myadmin/css/list.css" />


{% endblock %}

templates/yimi_admin/activity_list.html
{% extends "yimi_admin/base.html" %}
{% block right_div %}
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>管理</h6>
                    
                </div>
            </div>

            <div class="widget">
                              
                <ul class="options-bar">
                    <li>
                        <div class="  align-left">
                        <div class="bar-button"><button type="button" class="btn" onclick="location.href='{% url 'yimi_admin:activity_add' %}'" >创建活动</button>链接：http://{{appitem.domain}}{% url 'nanjing:activity_list' appitem.slug %}</div>
                        </div>  
                    </li>
                </ul>

            </div>
            <!-- /options bar -->                            
            <div class="table-overflow">
                <table class="table table-striped table-bordered table-checks media-table">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkRow" class="styled all-select" style="width:16px"/></th>
                            <th>活动名称</th>
                            <th>活动时间</th>
                            <th>活动人数</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for activity in activities %}
                        <tr>
                            <th><input type="checkbox" name="artwork_ids[]" class="styled" style="width:16px"  /></th>

                           <td><a href="{% url 'yimi_admin:activity_account_list' activity.id %}">{{activity.title}}</a></td>
                           <td>{{activity.a_time}}</td>
                           <td>{{activity.count}}</td>
                           <td>{% if activity.status %}发布{% else %}下线{% endif %}</td>
                           <td>
                            <input type="button" value="删除" onclick="location.href='{% url 'yimi_admin:activity_delete' activity.id %}'" />
                            <input type="button" value="编辑" onclick="location.href='{% url 'yimi_admin:activity_add' %}?aid={{activity.id}}'"/>
                            <input type="button" value="{% if activity.status %}下线{% else %}发布{% endif %}" onclick="location.href='{% url 'yimi_admin:activity_status' activity.id %}'"/>
                           </td>
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="/static/myadmin/css/list.css" />


{% endblock %}

templates/yimi_admin/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>接点平台 业务管理后台</title>
<link href="/static/myadmin/css/main.css" rel="stylesheet" type="text/css" />
<link href="/static/myadmin/css/mainstyle.css" rel="stylesheet" type="text/css" />


 <!--<link href="/static/bootstrap/assets/css/bootstrap.css" rel="stylesheet" type="text/css" /> -->
<link href="/static/myadmin/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
<!--[if IE 8]><link href="/static/watch/css/ie8.css" rel="stylesheet" type="text/css" /><![endif]-->
<!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'> -->

<script src="http://libs.baidu.com/jquery/1.8.2/jquery.js"></script>
<script src="http://libs.baidu.com/jqueryui/1.9.1/jquery-ui.min.js "></script>



<script type="text/javascript" src="/static/watch/js/plugins/forms/jquery.form.wizard.js"></script>
<script type="text/javascript" src="/static/watch/js/plugins/forms/jquery.form.js"></script>
<script type="text/javascript" src="/static/watch/js/plugins/tables/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="/static/myadmin/js/functions.js"></script>

<script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/static/ueditor/lang/zh-cn/zh-cn.js"></script>

</head>

<body >
    <div id="top">
        <div class="fixed">
        <div class="container">
            <a href="" title="" class="logo">接点平台 业务管理后台</a>
            <ul class="top-menu">
                <li class="dropdown">
                    <a class="user-menu" data-toggle="dropdown"><span>{{request.user.username}} <b class="caret"></b></span></a>
                    <a href="{% url 'yimi_admin:logout' %}" title=""id="sh_logout" class="user-menu" style="display:none;"><span>&nbsp;退出</span></a>
                </li>

            </ul>
        </div>
    </div>
    </div>

    <!-- Content container -->
    <div id="container" class="container row-fluid">

        <!-- Sidebar -->
        <div id="sidebar" class="span2">
            <div class="sidebar-tabs">
                <div id="general">
                    <!-- Main navigation -->
                    <ul class="navigation widget">
                        <li><a href="#" title="" class="expand subOpened"><i class="icon-reorder"></i>{{appitem.name}}<strong></strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:news_list' %}">文章管理</a></li>
                                <li><a href="{% url 'yimi_admin:news_add' %}">增加文章</a></li>
                                <li><a href="{% url 'yimi_admin:category_list' %}">分类管理</a></li>
                                <li><a href="{% url 'yimi_admin:articles_list' %}">文章分类管理</a></li>
                            </ul>
                        </li>
                         <li><a href="#" title="" class="expand"><i class="icon-reorder"></i>自动回复<strong>2</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:reply' %}?tag=subscribe">关注回复</a></li>
                                <li><a href="{% url 'yimi_admin:reply' %}?tag=keyword_default_recontent">无匹配回复</a></li>
                                <li><a href="{% url 'yimi_admin:keyword_reply' %}">关键字回复</a></li>
                            </ul>
                        </li>
                         <li><a href="{% url 'yimi_admin:users_list' %}" title="" class="expand"><i class="icon-reorder"></i>用户管理<strong>1</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:users_list' %}">用户管理</a></li>
                                <li><a href="{% url 'yimi_admin:groups_list' %}">组管理</a></li>
                            </ul>
                        </li>                        
                        <li><a href="#" title="" class="expand"><i class="icon-reorder"></i>自定义菜单<strong>2</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:menus_list' %}">菜单管理</a></li>
                                <li><a href="{% url 'yimi_admin:menu_add' %}">增加一级菜单</a></li>
                            </ul>
                        </li>                                                                       
                        <li><a href="#" title="" class="expand"><i class="icon-reorder"></i>用户提交信息管理<strong>3</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:activity_list' %}">活动管理</a></li>
                                <li><a href="{% url 'yimi_admin:open_account_list' %}">用户认证</a></li>
                                <li><a href="{% url 'yimi_admin:questions_list' %}">在线咨询</a></li>
                                <li><a href="{% url 'yimi_admin:proposal_list' %}">决议管理</a></li>
                            </ul>
                        </li>                          
                    </ul>
                    <!-- /main navigation -->
                </div>
            </div>
        </div>
        <!-- /sidebar -->
        <!-- Content -->
        {% block right_div %}
        {% endblock %}
        <!-- /content -->
    </div>

</body>
<script>
$(".top-menu").hover(
  function () {
    $("#sh_logout").css('display','block');
  },
  function () {
   $("#sh_logout").css('display','none');
  }
); 
</script>
</html>

templates/yimi_admin/menu_editor.html
{% extends "yimi_admin/base.html" %}
{% block right_div %}
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>{% if not menu_id %}新增一级菜单{% else %}修改一级菜单：{{menu.name}}{% endif %}</h6>
    
                </div>
            </div>
            <!-- /options bar -->    
            <div class="table-overflow">



<table class="mainTable">
      
      <tr>
        <td class="txtRight">名称：</td>
        <td><input id="menu-name" type="text" class="inputTxt w240" name="name" value={{menu.name|default:"默认名称"}} />
        <input type="button" value="保存修改名称" id="change-menu-name" class="inputTxt w240" /></td>
      </tr>
      <tr>
        <td class="txtRight">事件：</td>
        <td>
             <select id="type-select" class="inputTxt w240" >
                 <option>选择菜单事件类型</option>
                 <option value="click">关键字回复</option>
                 <option value="view">跳转链接</option>
                 <option value="sub_button">增加二级菜单</option>
             </select>
      </tr>
      <tr id="view-event" {% if menu.type != 'view' %} style="display:none" {% endif %} >
        <td class="txtRight">链接地址</td>
        <td>
            <form id="menu-url-form" method="post" action="{% url 'yimi_admin:menu_url' %}">{% csrf_token %}
            <input type="text" name="url" id="url-value" value="{{menu.url|default:''}}"  class="inputTxt w240"/>
            <input type="hidden" name="menuid" value="{{menu.id}}" />
            <input type="hidden" name="name" id="menu-name-url" />
            <input type="submit" name="提交"  class="inputTxt w240"/>
            </form>
        </td>
      </tr>
      
</table>


{% if message %}
<table  class="sh_table">
<tr>
    <td>{{message.keyword}}<td>
    <td>{% if message.retype == 'text' %}
        {{message.get_resource.content}}
        {% elif message.retype == 'news' %}
            {% for article in message.get_resource.articles.all %}
            <div>
                <p>{{article.title}}</p>
                <p><img src="{{article.get_image_url}}" width=100 height=100></p>
            </div>
            {% endfor %}
        {% endif %}
    </td>
</tr>
</table>
{% endif %}

<table class="sh_table">
{% for sub_menu in sub_menus %}
    <tr>
        <td>{{sub_menu.name}}</td>
    {% if sub_menu.type == 'view' %}
    <td>{{sub_menu.url}}</td>
    {% elif sub_menu.type == 'click' %}
    <td>{{sub_menu.get_message.keyword}}</td>
    {% endif %}
    <td><a href="{% url 'yimi_admin:sub_menu_update' %}?submenuid={{sub_menu.id}}&menuid={{menu.id}}">编辑<a></td>
    <td><a href="{% url 'yimi_admin:menu_delete' %}?menuid={{sub_menu.id}}&type=submenu">删除<a></td>
    </tr>
{% endfor %}
</table>


<div id="click-event" style="display:none" >

            <div class="navbar">
                <div class="navbar-inner">
                    <h6>关键字列表</h6>
    
                </div>
            </div>


                <table class="table table-striped table-bordered table-checks media-table">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkRow" class="styled all-select" style="width:16px"/></th>
                            <th>关键字</th>
                            <th>素材</th>
                            <th class="actions-column">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in messages %}
                        <tr>
                            <th><input type="checkbox" name="artwork_ids[]" class="styled" style="width:16px"  /></th>

                           <td>{{message.keyword}}</td>
                           <td>

                              {% if message.retype == 'text' %}
                              {{message.get_resource.content}}
                              {% elif message.retype == 'news' %}
                                  {% for article in message.get_resource.articles.all %}
                                  <div>
                                      <p>{{article.title}}</p>
                                  </div>
                                  {% endfor %}
                              {% endif %}
                            </td>
                           <td>
                            <input type="button" class="message-submit" value="选择" href-value="{% url 'yimi_admin:menu_click' %}?messageid={{message.id}}&type=menu&menuid={{menu.id}}"/>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


</div>




<script type="text/javascript">
$("#type-select").change(
    function(){
        if($(this).val()=="click"){
            $("#click-event").show();
            $("#view-event").hide();
            $("#subbutton-event").hide();
	   $("#change-menu-name").hide();
        }else if($(this).val()=="view"){
            $("#click-event").hide();
            $("#view-event").show();
            $("#subbutton-event").hide();
	   $("#change-menu-name").hide();
        }else if($(this).val()=="sub_button"){
            $("#click-event").hide();
            $("#view-event").hide();
            location.href="{% url 'yimi_admin:sub_menu_add' %}?menuid={{menu.id}}&name="+$("#menu-name").val();
        }
    }
)

$("#change-menu-name").click(
    function(){
        location.href = "{% url 'yimi_admin:menu_change_name' %}?menuid={{menu.id}}&tag=menu&name="+$("#menu-name").val()
}
)

$('.message-submit').click(
    function(){
       location.href = $(this).attr("href-value")+"&name="+$("#menu-name").val();
}
)
$("#menu-url-form").submit(
    function(){
        $("#menu-name-url").val($("#menu-name").val());
}
)

</script>


            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="/static/myadmin/css/list.css" />


{% endblock %}

templates/yimi_admin/users_list.html
{% extends "yimi_admin/base.html" %}
{% load tag_extras %}
{% block right_div %}
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>管理</h6>
                    
                </div>
            </div>

            <div class="widget">
                              
                <ul class="options-bar">
                    <li>
                        <div class="  align-left">
                            <div class="bar-button"><button type="button" class="btn" onclick="location.href='{% url 'yimi_admin:users_list' %}'" >全部用户</button></div>
                            <div class="bar-button"><button type="button" class="btn" onclick="location.href='{% url 'yimi_admin:users_list' %}?action_id=1'" >更新用户</button></div>
                            {% for app_group in app_groups %}
                            <div class="bar-button"><button type="button" class="btn btn-success" onclick="location.href='{% url 'yimi_admin:users_list' %}?group_id={{app_group.id}}'">{{app_group.name}}</button></div>
                            {% endfor %}
                        </div>  
                    </li>
                </ul>

            </div>
            <!-- /options bar -->                            
            <div class="table-overflow">

<div class="digg"><div class="sh_page" style="float:right;margin-top:3px;margin-bottom:9px;margin-right:-10px;">
{% if matchs.has_previous%}
<span><a href="?p={{matchs.previous_page_number }}">&lt; </span>
{%else%}
<span class="disabled">&lt; </span>
{%endif%}
{% for p in show_pages %}
<span ><a {% if p == matchs.number %} style="border:none; background-color:#333333;color:white;border-radius:5px;padding:5px 10px;"{% endif %}  href="?p={{p}}">{{p}}</a></span>
{% endfor %}

{% if matchs.has_next  %}  
<span ><a href="?p={{ matchs.next_page_number }}">&gt; </a></span>
{% else %}
<span class="disabled">&gt; </span>
{% endif %}
</div>



                <table class="table table-striped table-bordered table-checks media-table">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkRow" class="styled all-select" style="width:16px"/></th>
                            <th>用户名</th>
                            <th>所在组</th>
                            <th class="actions-column">加入组</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in matchs %}
                        <tr>
                            <th><input type="checkbox" name="artwork_ids[]" class="styled" style="width:16px"  /></th>

                           <td>{{user.nickname}}</td>
                           <td>
{% for app_group in app_groups %}
{% if user in app_group.app_users.all %}
{% if app_group.id < 3 %}
<li>{{app_group.name}} </li>
{% else %}
<li>{{app_group.name}} <a href="{% url 'yimi_admin:group_remove' %}?openid={{user.openid}}&groupid={{app_group.id}}">移除</a></li>
{% endif %}
{% endif %}
{% endfor %}
                           </td>
                           <td>
<select class="app-group-select" uservalue="{{user.openid}}">
<option>选择分组</option>
{% for app_group in app_groups %}
{% if user not in app_group.app_users.all %}
{% if app_group.id > 2 %}
<option value="{{app_group.id}}" >{{app_group.name}}</option>
{%endif%}
{% endif %}
{% endfor %}
</select>
                           </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="/static/myadmin/css/list.css" />

<script type="text/javascript">

$('#submit-group').click(
    function(){
        location.href="{% url 'yimi_admin:groups_add' %}?groupname="+$('#group-name-value').val();
})

$(".app-group-select").change(
    function(){
        location.href="{% url 'yimi_admin:group_update' %}?openid="+$(this).attr('uservalue')+'&groupid='+$(this).val();
    }   
)


</script>

{% endblock %}