apps/nanjing/urls.py
from django.conf.urls import patterns, include, url 

import views

urlpatterns = patterns('',
    url(r'^(\w+)/articles-list/(\d+)/$', views.articles_list, name='articles_list'),
    url(r'^(\w+)/article-detail/(\d+)/$', views.article_detail, name='article_detail'),
    url(r'^(\w+)/open-account/$', views.open_account, name='open_account'),
    url(r'^(\w+)/sim-account/$', views.sim_account, name='sim_account'),
    url(r'^(\w+)/activity-user/(\d+)/$', views.activity_user, name='activity_user'),
    url(r'^(\w+)/commit-success/$', views.commit_success, name='commit_success'),
    url(r'^(\w+)/activity-list/$', views.activity_list, name='activity_list'),
    url(r'^(\w+)/show_question/$', views.show_question, name='show_question'),
    url(r'^(\w+)/activity-add/$', views.activity_add, name='activity_add'),
    url(r'^(\w+)/proposal-add/$', views.proposal_add, name='proposal_add'),
    url(r'^(\w+)/proposal-list/$', views.proposal_list, name='proposal_list'),
    url(r'^(\w+)/proposal-show/(\d+)/$', views.proposal_show, name='proposal_show'),
    url(r'^(\w+)/proposal-seconded/(\d+)/$', views.proposal_seconded, name='proposal_seconded'),
    url(r'^(\w+)/proposal-discuss/(\d+)/$', views.proposal_discuss, name='proposal_discuss'),
    url(r'^(\w+)/proposal-vote/(\d+)/$', views.proposal_vote, name='proposal_vote'),
)

blog/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url 

import myadmin

urlpatterns = patterns('',
    url(r'^$', myadmin.news_list, name='news_list'),
    url(r'^category-list/$', myadmin.category_list, name='category_list'),
    url(r'^news-add/$', myadmin.news_add, name='news_add'),  #news意义已失效，但仍有。此处是添加,修改文章
    url(r'^article-detail/(\d+)/$', myadmin.article_detail, name='article_detail'),
    url(r'^articles-list/$', myadmin.articles_list, name='articles_list'),
    #url(r'^article-update/$', myadmin.article_update, name='article_update'),
    url(r'^article-delete/(\d+)/$', myadmin.article_delete, name='article_delete'),
    url(r'^login/$', myadmin.mylogin, name='login'),
    url(r'^logout/$', myadmin.mylogout, name='logout'),

    url(r'^reply/$', myadmin.reply, name='reply'),  #关注回复，无匹配回复, 关键字编辑
    url(r'^message-update/$', myadmin.message_update, name='message_update'),  #message的所有修改
    url(r'^keyword-reply/$', myadmin.keyword_reply, name='keyword_reply'),
    url(r'^users-list/$', myadmin.users_list, name='users_list'),
    url(r'^groups-list/$', myadmin.groups_list, name='groups_list'),
    url(r'^groups-delete/$', myadmin.groups_delete, name='groups_delete'),
    url(r'^group-name-update/$', myadmin.group_name_update, name='group_name_update'),
    url(r'^category-delete/$', myadmin.category_delete, name='category_delete'),
    url(r'^category-name-update/$', myadmin.category_name_update, name='category_name_update'),
    url(r'^category-add/$', myadmin.category_add, name='category_add'),
    url(r'^category-remove/$', myadmin.category_remove, name='category_remove'),

    url(r'^menus-list/$', myadmin.menus_list, name='menus_list'),
    url(r'^send-create-menu/$', myadmin.send_create_menu, name='send_create_menu'),
    url(r'^menu-add/$', myadmin.menu_add, name='menu_add'),
    url(r'^menu-update/$', myadmin.menu_update, name='menu_update'),
    url(r'^menu-click/$', myadmin.menu_click, name='menu_click'),
    url(r'^menu-url/$', myadmin.menu_url, name='menu_url'),
    url(r'^menu-delete/$', myadmin.menu_delete, name='menu_delete'),
    url(r'^menu-change-name/$', myadmin.menu_change_name, name='menu_change_name'),
    url(r'^sub-menu-update/$', myadmin.sub_menu_update, name='sub_menu_update'),
    url(r'^sub-menu-add/$', myadmin.sub_menu_add, name='sub_menu_add'),

    url(r'^text-update/$', myadmin.text_update, name='text_update'),
    url(r'^news-update/$', myadmin.news_update, name='news_update'),
   # url(r'^keyword-update/(\d+)/$', myadmin.keyword_update, name='keyword_update'),
    url(r'^keyword-add/$', myadmin.keyword_add, name='keyword_add'),
    url(r'^keyword-delete/$', myadmin.keyword_delete, name='keyword_delete'),
    url(r'^groups-add/$', myadmin.groups_add, name='groups_add'),
    url(r'^group-update/$', myadmin.group_update, name='group_update'),
    url(r'^group-remove/$', myadmin.group_remove, name='group_remove'),

    url(r'^activity-list/$', myadmin.activity_list, name='activity_list'),
    url(r'^open-account-list/$', myadmin.open_account_list, name='open_account_list'),
    url(r'^sim-account-list/$', myadmin.sim_account_list, name='sim_account_list'),


    url(r'^account-delete/(\w+)/(\d+)/$', myadmin.account_delete, name='account_delete'),
    url(r'^account-pass/(\w+)/(\d+)/$', myadmin.account_update, name='account_update'),
    url(r'^activity-add/$', myadmin.activity_add, name='activity_add'),
    url(r'^activity-delete/(\d+)/$', myadmin.activity_delete, name='activity_delete'),
    url(r'^activity-account-list/(\d+)/$', myadmin.activity_account_list, name='activity_account_list'),
    url(r'^activity-status/(\d+)/$', myadmin.activity_status, name='activity_status'),


    url(r'^questions-list/$', myadmin.questions_list, name='questions_list'),  #客服列表
    url(r'^answer-question/$', myadmin.answer_question, name='answer_question'),  #客服列表
    url(r'^kefu-delete/$', myadmin.kefu_delete, name='kefu_delete'),  #客服列表

    url(r'proposal-list/$', myadmin.proposal_list, name='proposal_list'),
    url(r'proposal-add/$', myadmin.proposal_add, name='proposal_add'),
    url(r'proposal-delete/(\d+)/$', myadmin.proposal_delete, name='proposal_delete'),
    url(r'proposal-item-list/(\d+)/$', myadmin.proposal_item_list, name='proposal_item_list'),
    url(r'proposal-status/(\d+)/$', myadmin.proposal_status, name='proposal_status'),
    url(r'proposal-threshold/(\d+)/$', myadmin.proposal_threshold, name='proposal_threshold'),
    url(r'proposal-seconded/(\d+)/$', myadmin.proposal_seconded, name='proposal_seconded'),
    url(r'proposal-discuss/(\d+)/$', myadmin.proposal_discuss, name='proposal_discuss'),
    url(r'proposal-vote/(\d+)/$', myadmin.proposal_vote, name='proposal_vote'),
    url(r'proposal-discussaction/(\d+)/$', myadmin.proposal_discuss_action, name='proposal_discuss_action'),
)

yimi/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from yimi.settings import TOKEN
from django.contrib import admin
admin.autodiscover()

from yimi.views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^%s/(\d+)/$'%TOKEN, 'blog.views.weixin_api', name='weixin_api'),
    url(r'^$', 'blog.views.message', name='message'),
    url(r'^yimi-admin/', include('blog.urls', namespace="yimi_admin")),
    url(r'^a/', include('apps.nanjing.urls', namespace="nanjing")), #appitem slug

    url(r'^myueditor/upload/$', 'myueditor.views.upload', name='upload'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^syncdb/$', syncdb),#增加URL路径
    url(r'^migratedb/$', migratedb),#增加URL路径
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/activity_list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{{appitem.name}}</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
</head>

<body>
	<div class="wrap">
	    {% for activity in matchs %}
    	<dl class="list_box" style="padding:30px;">
        	<dt style="font-size:40px;">{{activity.title}}</dt>
           {% if activity.a_time %} <dd>时间：{{activity.a_time}}</dd> {% endif %}
           {% if activity.xingshi %} <dd>形式：{{activity.xingshi}}</dd> {% endif %}
           {% if activity.place %} <dd>地点：{{activity.place}}</dd> {% endif %}
           {% if activity.speaker %} <dd>主讲：{{activity.speaker}}</dd> {% endif %}
          {% if activity.count %}  <dd style="margin-top:10px;">人数：{{activity.count}}</dd> {% endif %}
           {% if activity.content %} <dd>内容：{{activity.content|safe}}</dd> {% endif %}
            <dd style="height:30px;"><button style="float:right;width:100px;height:45px;"href="http://{{appitem.domain}}{% url 'nanjing:activity_user' appitem.slug activity.id %}">报名</button></dd>
        </dl>
        {% endfor %}
    </div>
    <div class="tools">
    	<a href="{% if matchs.has_previous %}?p={{matchs.previous_page_number }}{% endif %}" class="left">上一页</a>
        <a href="{% if matchs.has_next %}?p={{matchs.next_page_number}}{% endif %}" class="right click">下一页</a>
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
</head>
<body>
aaaa
<img src='/static/images/88b4a463ef9862ee71fe12c4b278e073a2d90687.jpg'/>
</body>