apps/nanjing/urls.py
from django.conf.urls import patterns, include, url 

import views

urlpatterns = patterns('',
    url(r'^(\w+)/articles-list/(\d+)/$', views.articles_list, name='articles_list'),
    url(r'^(\w+)/article-detail/(\d+)/$', views.article_detail, name='article_detail'),
    url(r'^(\w+)/open-account/$', views.open_account, name='open_account'),
    url(r'^(\w+)/sim-account/$', views.sim_account, name='sim_account'),
    url(r'^(\w+)/activity-user/(\d+)/$', views.activity_user, name='activity_user'),
    url(r'^(\w+)/commit-success/$', views.commit_success, name='commit_success'),
    url(r'^(\w+)/activity-list/$', views.activity_list, name='activity_list'),
    url(r'^(\w+)/show_question/$', views.show_question, name='show_question'),
    url(r'^(\w+)/activity-add/$', views.activity_add, name='activity_add'),
    url(r'^(\w+)/proposal-add/$', views.proposal_add, name='proposal_add'),
    url(r'^(\w+)/proposal-list/$', views.proposal_list, name='proposal_list'),
    url(r'^(\w+)/proposal-show/(\d+)/$', views.proposal_show, name='proposal_show'),
    url(r'^(\w+)/proposal-seconded/(\d+)/$', views.proposal_seconded, name='proposal_seconded'),
    url(r'^(\w+)/proposal-discuss/(\d+)/$', views.proposal_discuss, name='proposal_discuss'),
    url(r'^(\w+)/proposal-vote/(\d+)/$', views.proposal_vote, name='proposal_vote'),
)

blog/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url 

import myadmin

urlpatterns = patterns('',
    url(r'^$', myadmin.news_list, name='news_list'),
    url(r'^category-list/$', myadmin.category_list, name='category_list'),
    url(r'^news-add/$', myadmin.news_add, name='news_add'),  #news意义已失效，但仍有。此处是添加,修改文章
    url(r'^article-detail/(\d+)/$', myadmin.article_detail, name='article_detail'),
    url(r'^articles-list/$', myadmin.articles_list, name='articles_list'),
    #url(r'^article-update/$', myadmin.article_update, name='article_update'),
    url(r'^article-delete/(\d+)/$', myadmin.article_delete, name='article_delete'),
    url(r'^login/$', myadmin.mylogin, name='login'),
    url(r'^logout/$', myadmin.mylogout, name='logout'),

    url(r'^reply/$', myadmin.reply, name='reply'),  #关注回复，无匹配回复, 关键字编辑
    url(r'^message-update/$', myadmin.message_update, name='message_update'),  #message的所有修改
    url(r'^keyword-reply/$', myadmin.keyword_reply, name='keyword_reply'),
    url(r'^users-list/$', myadmin.users_list, name='users_list'),
    url(r'^groups-list/$', myadmin.groups_list, name='groups_list'),
    url(r'^groups-delete/$', myadmin.groups_delete, name='groups_delete'),
    url(r'^group-name-update/$', myadmin.group_name_update, name='group_name_update'),
    url(r'^category-delete/$', myadmin.category_delete, name='category_delete'),
    url(r'^category-name-update/$', myadmin.category_name_update, name='category_name_update'),
    url(r'^category-add/$', myadmin.category_add, name='category_add'),
    url(r'^category-remove/$', myadmin.category_remove, name='category_remove'),

    url(r'^menus-list/$', myadmin.menus_list, name='menus_list'),
    url(r'^send-create-menu/$', myadmin.send_create_menu, name='send_create_menu'),
    url(r'^menu-add/$', myadmin.menu_add, name='menu_add'),
    url(r'^menu-update/$', myadmin.menu_update, name='menu_update'),
    url(r'^menu-click/$', myadmin.menu_click, name='menu_click'),
    url(r'^menu-url/$', myadmin.menu_url, name='menu_url'),
    url(r'^menu-delete/$', myadmin.menu_delete, name='menu_delete'),
    url(r'^menu-change-name/$', myadmin.menu_change_name, name='menu_change_name'),
    url(r'^sub-menu-update/$', myadmin.sub_menu_update, name='sub_menu_update'),
    url(r'^sub-menu-add/$', myadmin.sub_menu_add, name='sub_menu_add'),

    url(r'^text-update/$', myadmin.text_update, name='text_update'),
    url(r'^news-update/$', myadmin.news_update, name='news_update'),
   # url(r'^keyword-update/(\d+)/$', myadmin.keyword_update, name='keyword_update'),
    url(r'^keyword-add/$', myadmin.keyword_add, name='keyword_add'),
    url(r'^keyword-delete/$', myadmin.keyword_delete, name='keyword_delete'),
    url(r'^groups-add/$', myadmin.groups_add, name='groups_add'),
    url(r'^group-update/$', myadmin.group_update, name='group_update'),
    url(r'^group-remove/$', myadmin.group_remove, name='group_remove'),

    url(r'^activity-list/$', myadmin.activity_list, name='activity_list'),
    url(r'^open-account-list/$', myadmin.open_account_list, name='open_account_list'),
    url(r'^sim-account-list/$', myadmin.sim_account_list, name='sim_account_list'),


    url(r'^account-delete/(\w+)/(\d+)/$', myadmin.account_delete, name='account_delete'),
    url(r'^account-pass/(\w+)/(\d+)/$', myadmin.account_update, name='account_update'),
    url(r'^activity-add/$', myadmin.activity_add, name='activity_add'),
    url(r'^activity-delete/(\d+)/$', myadmin.activity_delete, name='activity_delete'),
    url(r'^activity-account-list/(\d+)/$', myadmin.activity_account_list, name='activity_account_list'),
    url(r'^activity-status/(\d+)/$', myadmin.activity_status, name='activity_status'),


    url(r'^questions-list/$', myadmin.questions_list, name='questions_list'),  #客服列表
    url(r'^answer-question/$', myadmin.answer_question, name='answer_question'),  #客服列表
    url(r'^kefu-delete/$', myadmin.kefu_delete, name='kefu_delete'),  #客服列表

    url(r'proposal-list/$', myadmin.proposal_list, name='proposal_list'),
    url(r'proposal-add/$', myadmin.proposal_add, name='proposal_add'),
    url(r'proposal-delete/(\d+)/$', myadmin.proposal_delete, name='proposal_delete'),
    url(r'proposal-item-list/(\d+)/$', myadmin.proposal_item_list, name='proposal_item_list'),
    url(r'proposal-status/(\d+)/$', myadmin.proposal_status, name='proposal_status'),
    url(r'proposal-threshold/(\d+)/$', myadmin.proposal_threshold, name='proposal_threshold'),
    url(r'proposal-seconded/(\d+)/$', myadmin.proposal_seconded, name='proposal_seconded'),
    url(r'proposal-discuss/(\d+)/$', myadmin.proposal_discuss, name='proposal_discuss'),
    url(r'proposal-vote/(\d+)/$', myadmin.proposal_vote, name='proposal_vote'),
    url(r'proposal-discussaction/(\d+)/$', myadmin.proposal_discuss_action, name='proposal_discuss_action'),
)

yimi/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from yimi.settings import TOKEN
from django.contrib import admin
admin.autodiscover()

from yimi.views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^%s/(\d+)/$'%TOKEN, 'blog.views.weixin_api', name='weixin_api'),
    url(r'^$', 'blog.views.message', name='message'),
    url(r'^yimi-admin/', include('blog.urls', namespace="yimi_admin")),
    url(r'^a/', include('apps.nanjing.urls', namespace="nanjing")), #appitem slug

    url(r'^myueditor/upload/$', 'myueditor.views.upload', name='upload'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^syncdb/$', syncdb),#增加URL路径
    url(r'^migratedb/$', migratedb),#增加URL路径
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/nanjing/views.py
#coding:utf8
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.template import RequestContext

from blog.models import *
from blog.utils import get_user_openid
from blog.utils import get_entry_page, page_turning
from models import *

from tools.config import *

def get_appitem(slug):
    appitem = AppItem.objects.filter(slug=slug).first()
    return appitem



def article_detail(request, slug, id):
    appitem = get_appitem(slug)
    article = Article.objects.filter(id=id).first()
    # get open id from open URL
    open_id = request.GET.get('open_id')
    if open_id:
        article.url = article.url + '?open_id=' + open_id
    if not article:
        raise Http404
    context = { 
        'article': article,
        'appitem': appitem,
    }   
    return render_to_response('nanjing/article_detail.html', context,
        context_instance=RequestContext(request))

def articles_list(request, slug, id):
   # category = Category.objects.filter(id=id, status=True).first()
   # appitem = category.appitem_set.first()
    appitem = get_appitem(slug)
    code = request.GET.get("code", '')
   # openid = get_user_openid(appitem.appid, appitem.app_secret, code)
    openid = appitem.get_user_openid(request)
    category = appitem.categories.get(id=id)        
    if openid and code:
        user = AppUser.objects.get(openid=openid)
        if not category.status: #不显示的分类
            if appitem.app_groups.filter(app_users=user, status=True).exists():
                articles = category.articles.all()
            else:
                return render_to_response('nanjing/notavailable.html', {},
                    context_instance=RequestContext(request))
        else:
            articles = category.articles.all()
    elif not code:
        articles = category.articles.all()
    else:
        articles = []
            
    page = int(request.GET.get("p",1))
   # return_articles = get_entry_page(articles,10,page)
    matchs, show_pages = page_turning(articles, request, 4)
    context = { 
        'appitem': appitem,
        'articles': articles,
        'matchs': matchs,
    }   
    return render_to_response('nanjing/articles_list.html', context,
        context_instance=RequestContext(request))

def activity_add(request, slug):
    appitem = get_appitem(slug)
    activity = None
    if request.method == 'POST':
        title = request.POST.get('title')
        a_time = request.POST.get('a_time')
        count = request.POST.get('count')
        xingshi = request.POST.get('xingshi')
        place = request.POST.get('place')
        speaker = request.POST.get('speaker')
        content = request.POST.get('content')
        files = request.FILES.getlist('fileselect')
        activity = appitem.activity_set.create(
            title=title, 
            a_time=a_time, 
            count=count,
            xingshi = xingshi,
            place = place,
            speaker = speaker,
            content = content,
        )
        for f in files:
            image_obj = activity.activity_images.create(image = f)
            image_obj.get_image_url()
        return HttpResponseRedirect(reverse_url(slug))
    context = {
        'appitem': appitem,
        'activity': activity,
    }
    return render_to_response('nanjing/activity_add_form.html', context,
        context_instance=RequestContext(request))

def reverse_url(slug):
    return reverse("nanjing:commit_success", args=(slug,))

def sim_account(request, slug):
    appitem = get_appitem(slug)
    if request.method == "POST":
        name = request.POST.get('name')
        cid = request.POST.get('cid')
        tel = request.POST.get('tel')
        simaccount = appitem.simaccount_set.filter(cid=cid).first()
        if not simaccount:
            appitem.simaccount_set.create(name=name, cid=cid, tel=tel)
            return HttpResponseRedirect(reverse_url(slug))
    context = {'appitem': appitem}
    
    return render_to_response('nanjing/sim_account_form.html', context,
        context_instance=RequestContext(request))

def open_account(request, slug):
    appitem = get_appitem(slug)
    if request.method == "POST":
        name = request.POST.get('name')
        cid = request.POST.get('cid')
        tel = request.POST.get('tel')
        lbs = request.POST.get('lbs')
        openid = request.POST.get('openid')
        # add the openaccount weixin open id unique check
        from django.db.models import Q
        openaccount = appitem.openaccount_set.filter(Q(cid=cid)|Q(openid=openid)).first()
        if not openaccount:
            # check if the openid is in the subscribed user list if not can not do verification
            openaccount = appitem.app_users.filter(openid=openid).first()
            if openaccount:
                appitem.openaccount_set.create(name=name, cid=cid, tel=tel, lbs=lbs, openid=openid)
                return HttpResponseRedirect(reverse_url(slug))
    elif request.method == "GET":
        open_id = request.GET.get('open_id')
        if open_id:
            context = {
                'appitem': appitem,
                'openid' : open_id,
            }
            return render_to_response('nanjing/open_account_form.html', context,
            context_instance=RequestContext(request))
    return return_fail(request, appitem, ERROR_NOTSUBSCRIBE_OR_ID_EXIST)


def return_fail(request, appitem, emsg):
    context = {
        'appitem': appitem,
        'emsg': emsg,
    }
    return render_to_response('nanjing/commit_fail.html', context,
        context_instance=RequestContext(request))


def activity_user(request, slug, cid):
    appitem = get_appitem(slug)
    activity = appitem.activity_set.filter(id=cid).first()
    if request.method == "POST":
        name = request.POST.get('name')
        cid = request.POST.get('cid')
        tel = request.POST.get('tel')
        lbs = request.POST.get('lbs')
       # openid = request.POST.get("openid")
       # if openid and activity.activity_users.filter(openid=openid).exists():
        activity.activity_users.create(name=name, cid=cid, tel=tel, lbs=lbs)
        return HttpResponseRedirect(reverse_url(slug))
    context = {'appitem': appitem, 'activity': activity}

    return render_to_response('nanjing/activity_user_form.html', context,
        context_instance=RequestContext(request))

def commit_success(request, slug):
    return render_to_response('nanjing/commit_success.html', {},
        context_instance=RequestContext(request))

def activity_list(request, slug):
    appitem = get_appitem(slug)
    activities = appitem.activity_set.filter(status=True)
    matchs, show_pages = page_turning(activities, request, 1)
    context = {'appitem': appitem, 'activities': activities, 'matchs': matchs}
    
    return render_to_response('nanjing/activity_list.html', context,
        context_instance=RequestContext(request))

def show_question(request, slug):
    '''客户服务'''
    appitem = get_appitem(slug)
    if request.method == 'POST':
        openid = request.POST.get('openid')
        question = request.POST.get('question')
        if openid:
            user = AppUser.objects.filter(openid=openid).first()
            if not user:
                user = AppUser.objects.create(openid=openid)
            KeFu.objects.create(appitem=appitem, appuser=user, question=question)
            return HttpResponseRedirect(reverse_url(slug))

    openid = appitem.get_user_openid(request)
    kefus = None
    if openid:
        user = AppUser.objects.filter(openid=openid).first()
        if not user:
            user = AppUser.objects.create(openid=openid)
        kefus = KeFu.objects.filter(appitem=appitem, appuser=user)
    context = {
        'kefus': kefus,
        'openid': openid,
        'appitem': appitem,
    }
    return render_to_response('nanjing/show_question.html', context,
        context_instance=RequestContext(request))

def proposal_add(request, slug):
    appitem = get_appitem(slug)
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        openid = request.POST.get('submitter')
        content = request.POST.get('content')
        amendment = request.POST.get('amendment_id')
        files = request.FILES.getlist('fileselect')
        openaccount = appitem.openaccount_set.get(openid=openid)
        if openaccount:
            submitter = openaccount.lbs
            proposal = appitem.proposal_set.create(
                title=title,
                openid=openid,
                amendment = amendment,
                submitter=submitter,
                content = content,
                description = description,
            )
            proposal.proposal_threshold.create()
            if files:
                for f in files:
                    image_obj = proposal.proposal_images.create(image = f)
                    image_obj.get_image_url()
            return HttpResponseRedirect(reverse_url(slug))
    elif request.method == "GET":
        open_id = request.GET.get('open_id')
        amendment = request.GET.get('amendment_id')
        if not amendment:
            amendment = 0
        if open_id:
            openaccount = appitem.openaccount_set.filter(openid=open_id).first()
            if openaccount:
                context = {
                    'appitem': appitem,
                    'openid' : open_id,
                    'openaccount': openaccount,
                    'amendment': amendment
                }
                return render_to_response('nanjing/proposal_add_form.html', context,
                context_instance=RequestContext(request))
    return return_fail(request, appitem, ERROR_NOTREGISTERED_USER)

def proposal_list(request, slug):

templates/nanjing/activity_add.html
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />
<script>
$(function() {

    $("input").blur(function() {
        if ($(this).val() == '') {
            $(this).next().addClass('visible');
        } else {
            $(this).next().removeClass('visible');
        }
    });

    $('.submit').click(function() {
        var a = 0;
        $('.sh_nes').each(function() {
            if ($(this).val() == '') {
                a = 1;
            }
        });
        if(a == 1){
       	alert('请完整填写表单');
        return false;
        }
    });
});
</script>

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>新增活动</h6>
                    
                </div>
            </div>

            <div class="widget">
                              
                <ul class="options-bar">
                    <li>
                        <div class="  align-left">


                        </div>  
                    </li>
                </ul>

            </div>
            <!-- /options bar -->                            


<form action="{% url 'nanjing:activity_add' apptiem.slug %}" method="post" >{% csrf_token %}
<table class="mainTable">
      
      <tr>
        <td class="txtRight">标题：</td>
        <td><input name="title" type="text" class="inputTxt w240 sh_nes" value="{{activity.a_title}}"  />*<span class="sh_error">请正确填写标题</span></td>
      </tr>
      <tr>
        <td class="txtRight">时间：</td>
        <td><input name="a_time" type="text" class="inputTxt w240 sh_nes" value="{{activity.a_time}}"/>*<span class="sh_error">请正确填写时间</span></td>
      </tr>
      <tr>
        <td class="txtRight">形式：</td>
        <td><input name="xingshi" type="text" class="inputTxt w240 sh_nes" value="{{activity.xingshi}}"/>*<span class="sh_error">请正确填写形式</span></td>
      </tr>
      <tr>
        <td class="txtRight">地点：</td>
        <td><input name="place" type="text" class="inputTxt w240 sh_nes" value="{{activity.place}}"/>*<span class="sh_error">请正确填写地点</span></td>
      </tr>
      <tr>
        <td class="txtRight">组织者：</td>
        <td><input name="speaker" type="text" class="inputTxt w240" value="{{activity.speaker}}"/></td>
      </tr>
      <tr>
        <td class="txtRight">人数：</td>
        <td><input name="count" type="text" class="inputTxt w240 sh_nes" value="{{activity.count|default:0}}"/>*<span class="sh_error">请正确填写人数</span></td>
      </tr>
      <tr>
        <td class="txtRight">内容：</td>
        <td>
        <script id="container-ueditor" name="content" type="text/plain">{{activity.content|safe}}</script>
        </td>      </tr>
   
      <tr>
        <td colspan="2" align="center"><input name="" type="submit" class="inputBut mr10 submit"  value="提交"/></td>
      </tr>
      
</table>
</form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var editor = UE.getEditor('container-ueditor')
</script>



<link rel="stylesheet" href="/static/myadmin/css/list.css" />

templates/nanjing/activity_add_form.html
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />
<script>
$(function() {

    $("input").blur(function() {
        if ($(this).val() == '') {
            $(this).next().addClass('visible');
        } else {
            $(this).next().removeClass('visible');
        }
    });

    $('.submit').click(function() {
        var a = 0;
        $('.sh_nes').each(function() {
            if ($(this).val() == '') {
                a = 1;
            }
        });
        if(a == 1){
       	alert('请完整填写表单');
        return false;
        }
    });
});
</script>

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>新增活动</h6>
                    
                </div>
            </div>
            <!-- /options bar -->                            


<form action="{% url 'nanjing:activity_add' appitem.slug %}" method="post" enctype='multipart/form-data'>{% csrf_token %}
<table class="mainTable">
      
      <tr>
        <td class="txtRight">标题：</td>
        <td><input name="title" type="text" class="inputTxt w240 sh_nes" value="{{activity.a_title}}"  />*<span class="sh_error">请正确填写标题</span></td>
      </tr>
      <tr>
        <td class="txtRight">时间：</td>
        <td><input name="a_time" type="text" class="inputTxt w240 sh_nes" value="{{activity.a_time}}"/>*<span class="sh_error">请正确填写时间</span></td>
      </tr>
      <tr>
        <td class="txtRight">形式：</td>
        <td><input name="xingshi" type="text" class="inputTxt w240 sh_nes" value="{{activity.xingshi}}"/>*<span class="sh_error">请正确填写形式</span></td>
      </tr>
      <tr>
        <td class="txtRight">地点：</td>
        <td><input name="place" type="text" class="inputTxt w240 sh_nes" value="{{activity.place}}"/>*<span class="sh_error">请正确填写地点</span></td>
      </tr>
      <tr>
        <td class="txtRight">组织者：</td>
        <td><input name="speaker" type="text" class="inputTxt w240" value="{{activity.speaker}}"/></td>
      </tr>
      <tr>
        <td class="txtRight">人数：</td>
        <td><input name="count" type="text" class="inputTxt w240 sh_nes" value="{{activity.count|default:0}}"/>*<span class="sh_error">请正确填写人数</span></td>
      </tr>
      <tr>
        <td class="txtRight">内容：</td>
        <td>
        <textarea id="textArea" name="content" type="text/plain" cols=40 rows=20>{{activity.content|safe}}</textarea>
        </td>
      </tr>
</table>

<div class="upload_main">
    <div style="border-bottom:1px solid #fff;" class="txtRight">上传活动图片(最多三张,不大于5M)：</div>
    <div class="upload_choose">
        <input id="Image" type="file" size="30" name="fileselect" multiple />
    </div>
    <div id="preview" class="upload_preview"></div>
</div>
<table>
<tr>
    <td colspan="2" align="center"><input name="" type="submit" class="inputBut mr10 submit"  value=">提交"/></td>
</tr>
</table>
</form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var editor = UE.getEditor('container-ueditor')
</script>
<script src="/static/zxxFile.js"></script>

<script>
var params = {
	fileInput: $("#Image").get(0),
	url: $("#uploadForm").attr("action"),
	filter: function(files) {
		var arrFiles = [];
		for (var i = 0, file; file = files[i]; i++) {
                        if (i>2) break;
			if (file.type.indexOf("image") == 0) {
				if (file.size >= 5120000) {
					alert('您这张"'+ file.name +'"图片大小过大，应小于5M');	
				} else{ 
                                        arrFiles.push(file);	
                                }
			} else {
				alert('文件"' + file.name + '"不是图片。');	
			}
		}
		return arrFiles;
	},
	onSelect: function(files) {
		var html = '', i = 0;
		$("#preview").html('<div class="upload_loading"></div>');
		var funAppendImage = function() {
			file = files[i];
			if (file) {
				var reader = new FileReader()
				reader.onload = function(e) {
					html = html + '<div id="uploadList_'+ i +'" class="upload_append_list"><p><strong>' + file.name + '</strong>'+ 
						'<a href="javascript:" class="upload_delete" title="删除" data-index="'+ i +'">删除</a><br />' +
						'<img id="uploadImage_' + i + '" src="' + e.target.result + '" class="upload_image" /></p>'+ 
						'<span id="uploadProgress_' + i + '" class="upload_progress"></span>' +
					'</div>';
					
					i++;
					funAppendImage();
				}
				reader.readAsDataURL(file);
			} else {
				$("#preview").html(html);
				if (html) {
					//删除方法
					$(".upload_delete").click(function() {
						ZXXFILE.funDeleteFile(files[parseInt($(this).attr("data-index"))]);
						return false;	
					});
					//提交按钮显示
					$("#fileSubmit").show();	
				} else {
					//提交按钮隐藏
					$("#fileSubmit").hide();	
				}
			}
		};
		funAppendImage();		
	},
	onDelete: function(file) {
		$("#uploadList_" + file.index).fadeOut();
	},
	onDragOver: function() {
		$(this).addClass("upload_drag_hover");
	},
	onDragLeave: function() {
		$(this).removeClass("upload_drag_hover");
	},
	onProgress: function(file, loaded, total) {
		var eleProgress = $("#uploadProgress_" + file.index), percent = (loaded / total * 100).toFixed(2) + '%';
		eleProgress.show().html(percent);
	},
	onSuccess: function(file, response) {
		$("#uploadInf").append("<p>上传成功，图片地址是：" + response + "</p>");
	},
	onFailure: function(file) {
		$("#uploadInf").append("<p>图片" + file.name + "上传失败！</p>");	
		$("#uploadImage_" + file.index).css("opacity", 0.2);
	},
	onComplete: function() {
		//提交按钮隐藏
		$("#fileSubmit").hide();
		//file控件value置空
		$("#fileImage").val("");
		$("#uploadInf").append("<p>当前图片全部上传完毕，可继续添加上传。</p>");
	}
};
ZXXFILE = $.extend(ZXXFILE, params);
ZXXFILE.init();
</script>


<link rel="stylesheet" href="/static/myadmin/css/list.css" />

templates/nanjing/open_account_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<meta name="viewport" content="width=device-width, initial-scale=1">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="user-scalable=no" />
<title>申请认证</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
</head>

<body >
	<div class="formWrap">
	    <form action="{% url 'nanjing:open_account' appitem.slug %}" method="post">{%csrf_token%}
    	<ul class="formList">
        	<li class="title">申请认证：</li>
            <li><input name="name" type="text"  class="inputTxt" placeholder="姓名"/></li>
            <li><input name="cid" type="text"  class="inputTxt" placeholder="身份证号"/></li>
            <li><input name="tel" type="text"  class="inputTxt" placeholder="手机号"/></li>
            <li><input name="lbs" type="text"  class="inputTxt" placeholder="居住房号 ex:15#2101"/></li>
            <li><input name="openid" type="hidden"  class="inputTxt" value="{{openid}}" readonly="true"/></li>
            <li><input name="" type="submit" class="inputBut" value="提交" /></li>
        </ul>
        </form>
    </div>
            <script>
	$(function(){
		$(".inputBut").click(function(){
			$("input").each(function(){
				if($(this).val()==''){
			alert('请完整输入信息');
			return false;
			}	
			});
		});
});
       </script>
</body>
</html>